Define a better name for main module
ambanum/OpenTermsArchive pull request #709
Opened 2021-11-25 16:46 UTC by Ndpnt

It makes code easier to understand by clarifying boundaries between `archivist` module and `open-terms-archive` app.

2021-11-29 22:51 UTC, MattiSG requested changes
Typo in function name 😅

2021-11-29 22:51 UTC, MattiSG commented on src/index.js
> +(async function OpenTermArchive() {
```suggestion
(async function startOpenTermsArchive() {
```

2021-11-29 22:52 UTC, MattiSG approved these changes
👍

2021-11-30 06:28 UTC, martinratinaud approved these changes
Test on local.

2021-11-30 08:01 UTC, merged