Improve CLI
ambanum/OpenTermsArchive pull request #951
Opened 2022-10-10 13:20 UTC by Ndpnt

Improve CLI and add possibility to specify document types

<img width="958" alt="Capture d’écran 2022-10-10 à 15 19 10" src="https://user-images.githubusercontent.com/1098708/194875720-47c9faf2-58cc-4a03-aeb5-f1730a9b3222.png">

2022-10-11 05:36 UTC, martinratinaud requested changes
In order to keep consistency, all the commander code should also be used in the `bin/track.js` so that this feature is available to all declaration repos.

The above change will need to change all declarations package script `test:modified` and `track:modified`

This is a very nice addition, thanks.

2022-10-11 05:36 UTC, martinratinaud commented on README.md
> +To disaply help:
```suggestion
To display help:
```

2022-10-11 07:00 UTC, Ndpnt commented
> A nice plus (or other PR) would be to

?

2022-10-11 07:22 UTC, clementbiron approved these changes

2022-10-11 07:22 UTC, clementbiron commented on README.md
```suggestion
To get the latest version of a specific service's terms and document type:

npm start -- --services <service_id> -d <document_type>
```

2022-10-11 07:23 UTC, clementbiron commented
I feel like it's Christmas, thanks!

2022-10-11 08:08 UTC, Ndpnt commented
Declarations template and other declarations repositories should be updated with:
`"track:modified": "git diff --name-only HEAD $(git merge-base HEAD origin/main) -- ./declarations/ | grep -v .history | grep -v .filters | sed 's/declarations\\///g' | sed 's/.json//g' | sed 's/.*/\"&\"/' | xargs -r npm run track -- -s"`

2022-10-17 09:40 UTC, martinratinaud approved these changes
I am not a big fan of the double dash but could not find a way out.

For reference, here is [an article](https://medium.com/fhinkel/the-curious-case-of-double-dashes-b5e7711698f) that explains it.

In all declarations repo, users will now need to use `npm run track -- -s <service_id> and tests scripts should be modified in all repos

2022-10-18 08:33 UTC, merged