Handle all cases of email protection to prevent blinking and ease maintenance
ambanum/OpenTermsArchive pull request #959
Opened 2022-11-01 05:03 UTC by martinratinaud

Here is an implementation of a global filter that aims at removing blink on several documents in an harmonized way.

For now, there has been an implementation that does not cover all cases and this lack of universality in the process is causing blinks on several instances and forcing contributors to [create a filter](https://github.com/OpenTermsArchive/p2b-compliance-declarations/blob/main/declarations/Fairbnb.coop.filters.js) for which we already have at least 3 versions.

Here are some affected documents

- [BlaBlaCar](https://github.com/OpenTermsArchive/france-versions/commit/724461ac41466ec152eb2501a7b0eb93b7821cb9)
- Cityscoot on France
- FairCoop on P2B
- and many others

Thanks to this PR, blink will not occur anymore on any instance and will remove the need of custom filters, thus improcing stability and maintainability

2022-11-01 10:40 UTC, MattiSG requested changes
Thanks @martinratinaud for this improvement suggestion! Indeed, these email protection practices are often a source of blinks and since they seem very similar, it would make sense to consolidate one “best” way to handle them.

However, the notion of “global filters” has not been properly defined yet, and I don't think they are a very good idea. I would prefer that we, for example, offer a standard library of common filters that users can then activate if needed (see this [🔒 draft issue](https://github.com/orgs/ambanum/projects/1/views/4?filterQuery=windstream)), or that we add a verb in declarations. In any case, having hidden, invisible transformations made on content is dangerous and can lead to very hard to diagnose issues on specific documents.

In any case, the test cases updated here do not demonstrate the improvements proposed.

Let's discuss this with @Ndpnt  🙂

2022-11-01 13:32 UTC, martinratinaud commented
Noted.

I hope we find a way to handle this easily as if it was to be removed, it would create many blinks that would make maintenance harder.

Concerning the test case, it has been replaced by the new way of handling this kind of links so I'm not sure what you mean by 

> the test cases updated here do not demonstrate the improvements proposed

Can you please be more specific?

2022-11-15 10:24 UTC, Ndpnt approved these changes

2022-11-22 16:22 UTC, martinratinaud commented
@MattiSG asked to rewrite the test cases but I have a workshop tomorrow and have no time to take care of that now.

Feel free to change it if you find the time.

2022-12-12 17:54 UTC, martinratinaud commented
@Ndpnt on [this snapshot](https://github.com/OpenTermsArchive/france-snapshots/commit/c7bfe571ad431032e3bb3c028d3a8304962a27ec), line 616

`<a href="/cdn-cgi/l/email-protection#2d4e4243594c4e596d4e4459545e4e424259034858">conta<span class="__cf_email__" data-cfemail="87e4f3c7e4eef3fef4e4e8e8f3a9e2f2">[email&#160;protected]</span></a>`, 

You can see the `conta<span` 

In the previous version, the code was only replacing the `href` whereas this version replaces the whole content of the `a`.

It is true though that it will not work on `BlaBlaCar` as the link is http://dataprotection@blablacar.com.
Maybe we should add a test for `dataprotection@*`

I pushed a test for this behaviour

let me know if it's alright

2022-12-13 08:40 UTC, MattiSG approved these changes

2022-12-13 10:49 UTC, merged